import './DevTools.css'

export const DevTools = () => {
  const link = 'https://github.com/paulcoding810/gen-ext'

  return (
    <main>
      <h3>DevTools Page</h3>
      <a href={link} target="_blank" rel="noreferrer">
        generated by gen-ext
      </a>
    </main>
  )
}

export default DevTools
