name: Build Template

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./template
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('template/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Chrome artifacts
        run: pnpm zip

      - name: Create Firefox artifacts
        run: pnpm zip:firefox

      - uses: actions/upload-artifact@v5
        with:
          name: extensions
          path: template/package/*
