name: Build Template

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./template
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create Chrome artifacts
        run: npm run zip

      - name: Create Firefox artifacts
        run: npm run zip:firefox

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: extensions
          path: template/package/*
